### ISSUE TITLE
question versioning - drop the leftover table columns for question table

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#221]

**Comment by guillogo** [comment]
Hi, PR created https://github.com/catalyst/moodle-MDL-70329/pull/250 in order to drop question fields.

After discussing this with @safatshahin the merge can be done after some changes that we're doing right now:

https://github.com/catalyst/moodle-MDL-70329/issues/191
https://github.com/catalyst/moodle-MDL-70329/issues/194
https://github.com/catalyst/moodle-MDL-70329/issues/189

Thank you.
