### ISSUE TITLE
Behat: qbank_preview - preview_question.feature

### ISSUE THREAD

**Issue by mattporritt** [catalyst/moodle-MDL-70329#351]
on line 31 "Scenario: Question preview shows the question and other information" could we add

    And I should see "Preview Options"

    And I should see "Comments"

    And I should see "Add a comment" (or have we buttons here now?)

    And I should see "ID number"

    And I should see "question type icon"

    And I should see "version"

    And I should see "question version"

    And I should see "the cog wheel icon" --> could we also add a behat test for the navigation? something like Scenario: I click on the cog weehl > And I should see [all titles]

    could we add another scenario "Scenario: Preview lets teacher change question version" (to work, this need some more background = Given the following question versions exist (add at least two verisons)

    When I set the fiel "question version" to "2"

    And I press "Update preview options" (not sure this is needed)

    Then the question version in the title line changes to "version 2"

    And the text in the question preview field changes --> or does this need to be a QAtest? (reading through comments behat I think it should work when the test includes creating the version and it is clear what text should be in version 2 (of course needs to be different from version 1)) 

https://github.com/moodle/moodle/blob/master/question/bank/previewquestion/tests/behat/preview_question.feature

**Comment by marcghaly** [comment]
Hi @safatshahin @mattporritt here is the branch for this issue: https://github.com/catalyst/moodle-MDL-70329/tree/master_MDL-71696-versioning-mod_quiz-193-328-351
I did not add the following scenario `Scenario: Preview lets teacher change question version` because one is doing the exact same thing as the desired behaviour, I renamed it so it is clearer `Scenario: Question version is updated when edited and teacher can change question version`
Thank you
