### ISSUE TITLE
Migrate existing qbank into a new plugin qbank structure

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-MDL-70329#5]
See https://docs.google.com/document/d/1W-VZV1XgtQWo0QQytfz536YTiSBOkjSagroc9ZcJDDE/edit# for the reference on proposed structure

**Comment by dmitriim** [comment]
this may be too broad so we may wan to split it a bit more...

**Comment by mattporritt** [comment]
Hi @timhunt ,
In terms of existing Moodle functionality, do you have a list (complete or otherwise) of Question bank functionality that should be moved into qbank_* plugins?
There will be more that are completed as part of the project, but for a start I want to concentrate on existing functionality.

Cheers,
Matt P

**Comment by timhunt** [comment]
I made an attempt to brain-dump it here: https://docs.google.com/document/d/1_PcbDOPbcqeiEPtglm2Tsx6YIJypcKOOlAir2lc4D_8/edit#heading=h.63uewwhnzgk4

Current display of the list of questions table is these classes, which gives you another list. (Re those classes, note https://tracker.moodle.org/browse/MDL-64076. We should use the right namespaces for the new code we write.)

I hope that is a good enought answer.

**Comment by mattporritt** [comment]
Thanks very much @timhunt perfect answer

**Comment by mattporritt** [comment]
Hi @safatshahin assigning this to you as it is related to: #4

**Comment by safatshahin** [comment]
Commenting for development reference:
restructure is done inside the following branch: https://github.com/catalyst/moodle-MDL-70329/tree/master_MDL-71378-%235
his branch includes some major code movement to follow the new design, changes to alias, moving classes to local/bank, changes to view.php etc. Anything related to features like edit, delete etc need to go ahead of this branch.

**Comment by safatshahin** [comment]
Branch for this issue:
https://github.com/catalyst/moodle-MDL-70329/tree/master_MDL-71378-%235

The changes done:
Migrated the structure of question bank to the new design structure
Deprecated the classes in the previous location
changed scripts like external, edit, etc to follow the new structure
made changes to hard coded structure and made changes to the view base to accept plugins as a column and row

a quick example can be found in this where i implemented the checkbox:
https://github.com/catalyst/moodle-MDL-70329/tree/master_MDL-71378-%2360

**Comment by mattporritt** [comment]
Hi @safatshahin ,
I think we need to split some things up so it's easier when we come to integrate.
Can we:
* [ ] Make a new branch: MDL-71526 that has all the "refactoring" work in it, rebased on top of Moodle core master branch
* [ ] Remove any code relating to any to this issue from the MDL-71378 branch and add it to the MDL-71526 branch. So there is a clean set of commits relating to just the creation of the new mod_qbank
* [ ] Rebase the: MDL-71378 branch against MDL-71526, so there is now a clean set of commits relating to just the creation of the new mod_qbank on top of the changes for MDL-71526
* [ ] Create a new branch: MDL-71516 from MDL-71378 and add the commits relating to the new qbank_* plugin type

Sorry, this is confusing.  We are doing this because, the first three trackers that will be integrated will be:

1. MDL-71526     Question bank: Refactor
2. MDL-71378     Question bank Activity: mod_qbank  
3. MDL-71516     Create new plugin type - Qbank

These need to be integrated in this order, and will be added one at a time.  So each code branch needs to build on top of the other. 
There is still going to be more rebasing here as the master branch that they are all based on will be also changing.

After that we will make branches and trackers for each of the qbank_* plugins, that will be based on MDL-71516

Cheers

**Comment by mattporritt** [comment]
I have updated the trackers with the git repo and diff urls.

**Comment by mattporritt** [comment]
@safatshahin is there anything else to do on this issue, or have the remaining tasks split out into individual issues

**Comment by safatshahin** [comment]
Hi @mattporritt 
Yes this issue splits into smaller parts.
