### ISSUE TITLE
Implement enable/disble for qbank plugins in plugin management

### ISSUE THREAD

**Issue by safatshahin** [catalyst/moodle-MDL-70329#66]

**Comment by abonaccorso** [comment]
@safatshahin this will only affect the qbank plugins adding features, not the basic qbank plugin, right? I am asking because it would be possible to disable question banks existing independent of quizzes. I don't know why one would like to do this, but the quiz would still work. But you cannot disable the question bank that belongs to a specific quiz. Unless the quiz is no longer working.

If my question should be unclear, please ask. I am not sure I was successfull in explaining well.

**Comment by safatshahin** [comment]
Hi @abonaccorso 
Thank you for your detailed explanation, really appreciate it. Yes it will only affect the qbank features, for example, if someone disables the delete plugin, no one will be able to delete a question.

**Comment by abonaccorso** [comment]
Hi @safatshahin 
Thanks for your explanation. Makes completely sense to me doing it this way.

**Comment by guillogo** [comment]
Hi,

I've added the enable/disable feature in `qbankplugins.php`

PR: https://github.com/catalyst/moodle-MDL-70329/pull/80

This feature will add a new record in config_plugin table if the plugin has been disabled.

Thank you.
Guillermo

**Comment by safatshahin** [comment]
closing this as implemented in #34
through pr #98
